name: frontend
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  flutter_joystick:
  firebase_core:
  firebase_database:
  fluttertoast:
  # agora_rtc_engine: ^6.0.4
  permission_handler:
  # agora_uikit: 1.0.4
  agora_rtc_engine: 1.0.5
  permission_handler: '^4.4.0+hotfix.2'  
  http: ^0.13.3  
  flutter_launcher_icons: "^0.11.0"
  wakelock: ^0.6.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
